name: "ppo"
lr: 3e-4
clip_epsilon: 0.2
gamma: 0.99
frames_per_batch: 1  # How much data to collect before updating
total_frames: 1    # Total training steps
num_epochs: 1         # How many times to learn from the same batch